runtime: python37
api_version: 1
threadsafe: true
entrypoint: gunicorn -p :8080 main:app

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
  
libraries:
  - name: ssl
    version: latest